### ISSUE TITLE
Migrate to Android Studio

### ISSUE THREAD

**Issue by eyob--** [MBHS-SPC/Blair-Talks#1]
This is technically an enhancement, but really, the fact that eclipse is even here is a bug. It's an enhancement, but a bug at heart. Anyways, I don't feel like assigning this to anyone, but someone: move this repo to Android Studio

**Comment by RobRoseKnows** [comment]
Migrated and submitted a pull request. Someone needs to test it.

PR https://github.com/MBHS-SPC/Blair-Talks/pull/2

**Comment by eyob--** [comment]
I tested it and confirm that the migration worked. Thanks, Robert!

I should add that I needed to change the compileSdkVersion in app/build.gradle to 21, since I didn't have 19.

PR was merged [here](https://github.com/MBHS-SPC/Blair-Talks/commit/59cb94f1c8b3c4c7c4e145d3b437ae7b0eaf3d00).
